In [40]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/final_merged_data_with_target.csv')

print('Dataset loaded successfully. Displaying the first 5 rows:')
display(df.head())

Dataset loaded successfully. Displaying the first 5 rows:

/tmp/ipykernel_4144/765177399.py:4: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/final_merged_data_with_target.csv')

,user_id,book_id,is_read,rating,date_added,date_updated,read_at,started_at,reading_duration_days,title,author_ids,author_names,average_rating,publication_year,description,genres,num_pages,original_title,original_publication_year,target
0,6ae8a47b5a7f8b0b145cf597a5d5c929,17342700,1,5,2016-12-21 11:23:08,2017-04-24 19:20:25,2017-04-24 00:00:00,2017-04-22 00:00:00,2.0,"Gathering Darkness (Falling Kingdoms, #3)",['5295120' '38531'],['Morgan Rhodes' 'Michelle Rowen'],4.32,2014.0,"In GATHERING DARKNESS, book three of the New Y...",['to-read' 'young-adult' 'currently-reading' '...,416.0,Gathering Darkness,2014.0,0.0
1,0c7429f150417a1af3c7045fc89a3f4e,18513581,1,3,2016-07-23 07:06:57,2017-01-01 17:40:35,2016-12-10 00:00:00,2016-12-02 00:00:00,8.0,"Young Avengers, Volume 2: Alternative Culture",['439887' '221821' '504788' '93125'],['Kieron Gillen' 'Jamie McKelvie' 'Kate Brown'...,4.18,2014.0,Ever wonder what the super hero equivalent of ...,['to-read' 'comics' 'graphic-novels' 'marvel' ...,112.0,"Young Avengers, Volume 2: Alternative Culture",2014.0,0.0
2,cd75b15c85a3dd27fef5ec3403a5f873,3993755,1,0,2017-06-30 08:33:08,2017-06-30 08:33:26,2017-06-30 08:33:26,2017-06-29 00:00:00,1.0,"Hail to the Chef (A White House Chef Mystery, #2)",['1020232'],['Julie Hyzy'],3.98,2008.0,White House executive chef Ollie Paras has to ...,['to-read' 'mystery' 'cozy-mystery' 'cozy-myst...,328.0,"Hail to the Chef (White House Chef Mystery, Bo...",2008.0,NaN
3,86b931f21144e8d743b40dc26f82073c,89724,1,4,2011-10-07 13:43:08,2011-11-03 20:05:41,2011-10-13 00:00:00,2011-10-07 00:00:00,6.0,We Have Always Lived in the Castle,['13388' '6404'],['Shirley Jackson' 'Jonathan Lethem'],4.04,2006.0,Merricat Blackwood lives on the family estate ...,['to-read' 'horror' 'fiction' 'favorites' 'cur...,146.0,We Have Always Lived in the Castle,1962.0,1.0
4,9adddbae754bf26fb04999a0f79f14c4,13565914,1,3,2013-01-03 18:42:59,2013-01-03 18:51:59,2013-01-04 18:51:59,2013-01-01 00:00:00,3.0,"Knight (Unfinished Hero, #1)",['2958084'],['Kristen Ashley'],3.94,2012.0,Anya Gage has learned that to get anything goo...,['to-read' 'favorites' 'romance' 'currently-re...,285.0,Knight,2012.0,1.0

## Basic Data Types

Let's inspect the data types of each column and convert them if necessary. This step is crucial for efficient memory usage and correct data manipulation.

In [42]:
print('Original data types:')
display(df.info())

Original data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82855 entries, 0 to 82854
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   user_id                    82855 non-null  object
 1   book_id                    82855 non-null  int64
 2   is_read                    82855 non-null  int64
 3   rating                     82855 non-null  int64
 4   date_added                 82855 non-null  object
 5   date_updated               82855 non-null  object
 6   read_at                    39771 non-null  object
 7   started_at                 39772 non-null  object
 8   reading_duration_days      39772 non-null  float64
 9   title                      82855 non-null  object
 10  author_ids                 82855 non-null  object
 11  author_names               82855 non-null  object
 12  average_rating             82848 non-null  float64
 13  publication_year           69943 non-null  float64
 14  description                79256 non-null  object
 15  genres                     82855 non-null  object
 16  num_pages                  71401 non-null  float64
 17  original_title             54195 non-null  object
 18  original_publication_year  79245 non-null  float64
 19  target                     71387 non-null  float64
dtypes: float64(6), int64(3), object(11)
memory usage: 12.6+ MB

None

## Date Cleaning

Next, I'll clean and standardize any date columns. This usually involves converting them to datetime objects for easier manipulation.

In [44]:
# Identify potential date columns
date_columns = ['date_added', 'date_updated', 'read_at', 'started_at']

for col in date_columns:
    if col in df.columns:
        print(f"Converting column '{col}' to datetime...")
        # Use errors='coerce' to turn unparseable dates into NaT (Not a Time)
        df[col] = pd.to_datetime(df[col], errors='coerce')
    else:
        print(f"Column '{col}' not found.")

print('\nData types after date conversion:')
display(df.info())

Converting column 'date_added' to datetime...
Converting column 'date_updated' to datetime...
Converting column 'read_at' to datetime...
Converting column 'started_at' to datetime...

Data types after date conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82855 entries, 0 to 82854
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   user_id                    82855 non-null  object
 1   book_id                    82855 non-null  int64
 2   is_read                    82855 non-null  int64
 3   rating                     82855 non-null  int64
 4   date_added                 82855 non-null  datetime64[ns]
 5   date_updated               82855 non-null  datetime64[ns]
 6   read_at                    39771 non-null  datetime64[ns]
 7   started_at                 39771 non-null  datetime64[ns]
 8   reading_duration_days      39772 non-null  float64
 9   title                      82855 non-null  object
 10  author_ids                 82855 non-null  object
 11  author_names               82855 non-null  object
 12  average_rating             82848 non-null  float64
 13  publication_year           69943 non-null  float64
 14  description                79256 non-null  object
 15  genres                     82855 non-null  object
 16  num_pages                  71401 non-null  float64
 17  original_title             54195 non-null  object
 18  original_publication_year  79245 non-null  float64
 19  target                     71387 non-null  float64
dtypes: datetime64[ns](4), float64(6), int64(3), object(7)
memory usage: 12.6+ MB

None

## Invalid Date Check

After converting to datetime objects, it's important to check for any invalid dates (represented as `NaT`) and decide how to handle them. For now, I'll just show the count of `NaT` values.

In [46]:
for col in date_columns:
    if col in df.columns:
        invalid_dates_count = df[col].isna().sum()
        if invalid_dates_count > 0:
            print(f"Column '{col}': {invalid_dates_count} invalid date(s) found (NaT).")
        else:
            print(f"Column '{col}': No invalid dates found.")

# Display rows with invalid dates for inspection
# For simplicity, let's just display a sample of rows where any of the identified date columns is NaT
# You might want to refine this to show specific columns or handle them differently
problematic_rows = df[df[date_columns].isna().any(axis=1)]
if not problematic_rows.empty:
    print('\nSample of rows with invalid dates:')
    display(problematic_rows.head())
else:
    print('\nNo rows with invalid dates across the identified date columns.')

Column 'date_added': No invalid dates found.
Column 'date_updated': No invalid dates found.
Column 'read_at': 43084 invalid date(s) found (NaT).
Column 'started_at': 43084 invalid date(s) found (NaT).

Sample of rows with invalid dates:

,user_id,book_id,is_read,rating,date_added,date_updated,read_at,started_at,reading_duration_days,title,author_ids,author_names,average_rating,publication_year,description,genres,num_pages,original_title,original_publication_year,target
5585,5fd55d9e4037d2833088c2c4b3e755ae,30046024,1,4,2016-12-28 21:52:05,2016-12-30 07:17:25,NaT,NaT,1.0,"Exhume (Dr. Schwartzman, #1)",['150675'],['Danielle Girard'],3.93,2016.0,Dr. Annabelle Schwartzman has finally found a ...,['to-read' 'kindle' 'currently-reading' 'myste...,399.0,Exhume,2016.0,NaN
39772,a261146780a2ba17fda64630d881bfc3,15985394,0,0,2013-04-03 16:40:49,2013-04-03 16:40:49,NaT,NaT,NaN,The Repeat Year,['6519007'],['Andrea Lochen'],3.54,2013.0,"Everyone has days, weeks, even months they wis...",['to-read' 'chick-lit' 'fiction' 'currently-re...,400.0,NaN,2013.0,0.0
39773,10d700ff8e03ddaea66ee44c061d59d3,24902492,0,0,2015-02-23 10:38:10,2017-03-20 15:50:23,NaT,NaT,NaN,Ruby,['6575052'],['Cynthia Bond'],3.63,2015.0,"The epic, unforgettable story of a man determi...",['to-read' 'currently-reading' 'fiction' 'hist...,368.0,Ruby,2014.0,0.0
39774,6ac4e570139ec7ad42f0e479d43bdb96,4292125,0,0,2010-04-05 16:39:12,2010-04-05 16:39:12,NaT,NaT,NaN,Charles and Emma: The Darwins' Leap of Faith,['119782'],['Deborah Heiligman'],3.68,NaN,Charles Darwin published The Origin of Species...,['to-read' 'non-fiction' 'biography' 'young-ad...,268.0,Charles and Emma: The Darwins' Leap of Faith,2008.0,0.0
39775,00a35cb9e41c157f561bf94f784328f3,22288,0,0,2016-10-07 22:01:11,2016-10-07 22:01:11,NaT,NaT,NaN,Haunted,['2546'],['Chuck Palahniuk'],3.59,2006.0,Haunted is a novel made up of stories: twenty-...,['to-read' 'fiction' 'horror' 'favorites' 'sho...,419.0,Haunted: A Novel of Stories,2005.0,0.0

## Page Cleaning

Now, let's address the `num_pages` column. This typically involves checking for missing values, incorrect data types, and any outliers that might be present.

In [48]:
print(f"Info for 'num_pages' column before cleaning:")
display(df['num_pages'].describe())
print(f"\nNumber of missing values in 'num_pages': {df['num_pages'].isnull().sum()}")
print(f"\nUnique values in 'num_pages' (first 20 if many):\n{df['num_pages'].value_counts(dropna=False).head(20)}")

# Convert 'num_pages' to numeric, coercing errors
df['num_pages'] = pd.to_numeric(df['num_pages'], errors='coerce')

# Handle missing values: fill with median or mean, or drop rows. For now, let's fill with the median.
# Consider the context before deciding on the best strategy for NaNs.
median_pages = df['num_pages'].median()
print(f"\nFilling missing 'num_pages' with median value: {median_pages}")
df['num_pages'].fillna(median_pages, inplace=True)

# Ensure 'num_pages' are integers (after handling potential float conversions from median/mean)
df['num_pages'] = df['num_pages'].astype(int)

print(f"\nInfo for 'num_pages' column after cleaning:")
display(df['num_pages'].describe())
print(f"\nNumber of missing values in 'num_pages' after cleaning: {df['num_pages'].isnull().sum()}")

Info for 'num_pages' column before cleaning:

count    71401.000000
mean       317.578689
std        164.682334
min          0.000000
25%        232.000000
50%        316.000000
75%        384.000000
max       6940.000000
Name: num_pages, dtype: float64

Number of missing values in 'num_pages': 11454

Unique values in 'num_pages' (first 20 if many):
num_pages
NaN      11454
320.0     1709
352.0     1529
384.0     1453
336.0     1404
304.0     1390
288.0     1269
368.0     1126
400.0     1043
256.0     1009
272.0      897
416.0      774
240.0      761
224.0      754
192.0      747
32.0       593
208.0      550
432.0      504
160.0      469
448.0      455
Name: count, dtype: int64

Filling missing 'num_pages' with median value: 316.0

Info for 'num_pages' column after cleaning:

/tmp/ipykernel_4144/3154741647.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['num_pages'].fillna(median_pages, inplace=True)

count    82855.000000
mean       317.360449
std        152.876996
min          0.000000
25%        250.000000
50%        316.000000
75%        371.000000
max       6940.000000
Name: num_pages, dtype: float64

Number of missing values in 'num_pages' after cleaning: 0

In [ ]:
df.shape

(82855, 21)

In [ ]:
df.shape
df.head()
# df.columns

,user_id,book_id,is_read,rating,date_added,date_updated,read_at,started_at,reading_duration_days,title,...,author_names,average_rating,publication_year,description,genres,num_pages,original_title,original_publication_year,target,genres_list
0,6ae8a47b5a7f8b0b145cf597a5d5c929,17342700,1,5,2016-12-21 11:23:08,2017-04-24 19:20:25,2017-04-24 00:00:00,2017-04-22,2.0,"Gathering Darkness (Falling Kingdoms, #3)",...,['Morgan Rhodes' 'Michelle Rowen'],4.32,2014.0,"In GATHERING DARKNESS, book three of the New Y...",['to-read' 'young-adult' 'currently-reading' '...,416,Gathering Darkness,2014.0,0.0,"[to-read, young-adult, currently-reading, fant..."
1,0c7429f150417a1af3c7045fc89a3f4e,18513581,1,3,2016-07-23 07:06:57,2017-01-01 17:40:35,2016-12-10 00:00:00,2016-12-02,8.0,"Young Avengers, Volume 2: Alternative Culture",...,['Kieron Gillen' 'Jamie McKelvie' 'Kate Brown'...,4.18,2014.0,Ever wonder what the super hero equivalent of ...,['to-read' 'comics' 'graphic-novels' 'marvel' ...,112,"Young Avengers, Volume 2: Alternative Culture",2014.0,0.0,"[to-read, comics, graphic-novels, marvel, grap..."
2,cd75b15c85a3dd27fef5ec3403a5f873,3993755,1,0,2017-06-30 08:33:08,2017-06-30 08:33:26,2017-06-30 08:33:26,2017-06-29,1.0,"Hail to the Chef (A White House Chef Mystery, #2)",...,['Julie Hyzy'],3.98,2008.0,White House executive chef Ollie Paras has to ...,['to-read' 'mystery' 'cozy-mystery' 'cozy-myst...,328,"Hail to the Chef (White House Chef Mystery, Bo...",2008.0,NaN,"[to-read, mystery, cozy-mystery, cozy-mysterie..."
3,86b931f21144e8d743b40dc26f82073c,89724,1,4,2011-10-07 13:43:08,2011-11-03 20:05:41,2011-10-13 00:00:00,2011-10-07,6.0,We Have Always Lived in the Castle,...,['Shirley Jackson' 'Jonathan Lethem'],4.04,2006.0,Merricat Blackwood lives on the family estate ...,['to-read' 'horror' 'fiction' 'favorites' 'cur...,146,We Have Always Lived in the Castle,1962.0,1.0,"[to-read, horror, fiction, favorites, currentl..."
4,9adddbae754bf26fb04999a0f79f14c4,13565914,1,3,2013-01-03 18:42:59,2013-01-03 18:51:59,2013-01-04 18:51:59,2013-01-01,3.0,"Knight (Unfinished Hero, #1)",...,['Kristen Ashley'],3.94,2012.0,Anya Gage has learned that to get anything goo...,['to-read' 'favorites' 'romance' 'currently-re...,285,Knight,2012.0,1.0,"[to-read, favorites, romance, currently-readin..."

## Genre String Parsing

The `genres` column appears to contain string representations of lists. I will parse these strings to actual Python lists for easier manipulation and analysis.

In [50]:
import ast
import re # Import the re module for regular expressions

print(f"Original type of 'genres' column: {df['genres'].dtype}")
print(f"Sample of original 'genres' data:\n{df['genres'].head()}")

# Function to parse genre strings using regex
def parse_genres(genre_str):
    if pd.isna(genre_str) or not isinstance(genre_str, str):
        return []
    # Use regex to find all strings enclosed in single quotes
    tags = re.findall(r"'([^']*)'", genre_str)
    return tags

df['genres_list'] = df['genres'].apply(parse_genres)

print(f"\nNew 'genres_list' column created. Sample of parsed 'genres_list' data:\n{df['genres_list'].head()}")
print(f"Type of 'genres_list' column: {df['genres_list'].dtype}")

# df = df.drop('genres', axis=1)

Original type of 'genres' column: object
Sample of original 'genres' data:
0    ['to-read' 'young-adult' 'currently-reading' '...
1    ['to-read' 'comics' 'graphic-novels' 'marvel' ...
2    ['to-read' 'mystery' 'cozy-mystery' 'cozy-myst...
3    ['to-read' 'horror' 'fiction' 'favorites' 'cur...
4    ['to-read' 'favorites' 'romance' 'currently-re...
Name: genres, dtype: object

New 'genres_list' column created. Sample of parsed 'genres_list' data:
0    [to-read, young-adult, currently-reading, fant...
1    [to-read, comics, graphic-novels, marvel, grap...
2    [to-read, mystery, cozy-mystery, cozy-mysterie...
3    [to-read, horror, fiction, favorites, currentl...
4    [to-read, favorites, romance, currently-readin...
Name: genres_list, dtype: object
Type of 'genres_list' column: object

## Shelf Tag List

From the `genres_list`, I will now identify and consolidate individual shelf tags. This will involve iterating through the lists and collecting all unique tags.

In [52]:
from collections import defaultdict

# Assuming 'genres_list' contains lists of genres
# If 'genres_list' is not yet created, the previous 'Genre String Parsing' cell needs to be run first.

all_shelf_tags = defaultdict(int)

for index, genre_list in df['genres_list'].items():
    if isinstance(genre_list, list):
        for tag in genre_list:
            all_shelf_tags[tag] += 1

print(f"Total unique shelf tags found: {len(all_shelf_tags)}")
print("Top 20 most frequent shelf tags:")
for tag, count in sorted(all_shelf_tags.items(), key=lambda item: item[1], reverse=True)[:20]:
    print(f"- {tag}: {count}")

Total unique shelf tags found: 87932
Top 20 most frequent shelf tags:
- to-read: 82154
- currently-reading: 75195
- favorites: 62995
- owned: 61229
- fiction: 61014
- kindle: 58889
- books-i-own: 56795
- ebook: 55344
- library: 51379
- to-buy: 47894
- ebooks: 47335
- wish-list: 44869
- owned-books: 44340
- romance: 43417
- series: 39949
- contemporary: 39246
- adult: 37455
- audiobook: 37334
- audiobooks: 34514
- default: 33694

## Remove Non-Genre Tags

Many tags in the `genres_list` might not represent actual genres but rather reader statuses or organizational labels (e.g., 'to-read', 'currently-reading'). This step aims to identify and remove these non-genre tags to focus on actual genre classifications.

In [54]:
from itertools import chain

# Define a list of common non-genre tags to be removed
# This list can be expanded based on further data exploration
non_genre_tags = [
    'to-read',
    'currently-reading',
    'read',
    'favorites',
    'kindle',
    'audiobook',
    'ebook',
    'library',
    'owned',
    'default',
    'my-books',
    'wishlist',
    'audio'
]

# Create a new column for cleaned genres
df['cleaned_genres'] = df['genres_list'].apply(lambda genres:
    [tag for tag in genres if tag not in non_genre_tags]
)

# Display some samples before and after cleaning
print("Sample of genres before and after cleaning:")
for i in range(5):
    print(f"Original: {df['genres_list'].iloc[i]}")
    print(f"Cleaned:  {df['cleaned_genres'].iloc[i]}\n")

# Update the all_shelf_tags to reflect the cleaned genres
all_cleaned_tags = defaultdict(int)
for tag in chain.from_iterable(df['cleaned_genres']):
    all_cleaned_tags[tag] += 1

print(f"Total unique cleaned genre tags found: {len(all_cleaned_tags)}")
print("Top 20 most frequent cleaned genre tags:")
for tag, count in sorted(all_cleaned_tags.items(), key=lambda item: item[1], reverse=True)[:20]:
    print(f"- {tag}: {count}")

Sample of genres before and after cleaning:
Original: ['to-read', 'young-adult', 'currently-reading', 'fantasy', 'books-i-own', 'ya', 'magic', 'favorites', 'romance', 'series', 'ya-fantasy', 'to-buy', 'favourites', 'read-in-2016', 'read-in-2015', 'adventure', 'falling-kingdoms', 'owned', 'read-2016', 'read-in-2017', 'fiction', '2014-releases', 'library', 'high-fantasy', 'wish-list', 'i-own', 'ebook', 'audiobook', '2016-reads', 'my-books', '2015-reads', '5-stars', 'ebooks', 'owned-books', 'witches', 'royalty', 'audiobooks', 'kindle', 'tbr-pile', 'morgan-rhodes', 'epic-fantasy', '4-stars', 'need-to-buy', 'owned-tbr', '2014-release', 'read-in-english', 'love-triangle', 'favorite-books', 'paranormal', 'read-2017', '2017-reads', 'multiple-pov', 'ya-fiction', 'books-to-buy', 'must-read', 'e-books', 'favorite-series', 'unfinished-series', 'hardcover', 'young-adult-fantasy', '2017-tbr', 'all-time-favorites', 'favorite', 'tbr-owned', 'audio', 'fantasy-romance', 'teen', 'book-boyfriends', 'cover-love', 'series-to-finish', 'want-to-own', 'want-to-buy', 'tbr', 'english', '2015-favorites', 'medieval', 'action', 'book-boyfriend', 'cliffhanger', 'my-bookshelf', 'default', 'own-to-read', '2016-read', 'on-my-bookshelf', 'war', 'on-my-shelves', 'bought', 'signed', 'beautiful-covers', 'sci-fi-fantasy', 'assassins', 'reviewed', 'otp', 'read-in-2014', 'fantasy-magic', 'kingdoms', 'lgbt', 'books-i-have', 'dnf', 'have']
Cleaned:  ['young-adult', 'fantasy', 'books-i-own', 'ya', 'magic', 'romance', 'series', 'ya-fantasy', 'to-buy', 'favourites', 'read-in-2016', 'read-in-2015', 'adventure', 'falling-kingdoms', 'read-2016', 'read-in-2017', 'fiction', '2014-releases', 'high-fantasy', 'wish-list', 'i-own', '2016-reads', '2015-reads', '5-stars', 'ebooks', 'owned-books', 'witches', 'royalty', 'audiobooks', 'tbr-pile', 'morgan-rhodes', 'epic-fantasy', '4-stars', 'need-to-buy', 'owned-tbr', '2014-release', 'read-in-english', 'love-triangle', 'favorite-books', 'paranormal', 'read-2017', '2017-reads', 'multiple-pov', 'ya-fiction', 'books-to-buy', 'must-read', 'e-books', 'favorite-series', 'unfinished-series', 'hardcover', 'young-adult-fantasy', '2017-tbr', 'all-time-favorites', 'favorite', 'tbr-owned', 'fantasy-romance', 'teen', 'book-boyfriends', 'cover-love', 'series-to-finish', 'want-to-own', 'want-to-buy', 'tbr', 'english', '2015-favorites', 'medieval', 'action', 'book-boyfriend', 'cliffhanger', 'my-bookshelf', 'own-to-read', '2016-read', 'on-my-bookshelf', 'war', 'on-my-shelves', 'bought', 'signed', 'beautiful-covers', 'sci-fi-fantasy', 'assassins', 'reviewed', 'otp', 'read-in-2014', 'fantasy-magic', 'kingdoms', 'lgbt', 'books-i-have', 'dnf', 'have']

Original: ['to-read', 'comics', 'graphic-novels', 'marvel', 'graphic-novel', 'superheroes', 'favorites', 'comics-graphic-novels', 'young-adult', 'comic-books', 'marvel-comics', 'lgbt', 'ya', 'superhero', 'lgbtq', 'fiction', 'currently-reading', 'comics-and-graphic-novels', 'books-i-own', 'fantasy', 'read-in-2014', 'graphic-novels-comics', 'comic', 'owned', 'read-in-2015', 'avengers', 'marvel-now', 'read-in-2016', 'queer', 'lgbtqia', 'science-fiction', 'young-avengers', 'series', 'graphic-novels-and-comics', 'comics-read', 'sci-fi', 'library', 'comics-marvel', 'favourites', 'graphic', 'read-2016', '2015-reads', 'sequential-art', 'ebook', 'comics-manga', 'comic-book', 'glbt', 'read-2014', 'adventure', 'read-comics', '2016-reads', 'marvel-unlimited', 'lgbt-characters', 'manga-comics', 'contemporary', 'aliens', '5-stars', 'read-2015', 'comics-gn', 'magic', 'poc', 'english', 'teen', '2014-releases', 'comic-books-graphic-novels', 'romance', 'to-read-comics', 'read-in-2017', 'graphic-novels-read', 'library-books', 'wish-list', 'diversity', 'poc-characters', 'action', 'kindle', 'm-m', 'superhero-comics', 'super-heroes', 'read-in-english', 'comics-2014', 'queer-characters', 'comic-volumes', '3-stars', 'read-2017', 'lgbt-authors', 'diverse', 'type-comics', 'mythology', 'lgbtqa', 'diverse-books', 'comic-trades', 'graphic-novel-comic', '4-stars', 'comixology', '2014-reads', 'from-the-library', 'comics-to-read', 'trade-paperbacks', 'borrowed', 'comic-graphic-novel']
Cleaned:  ['comics', 'graphic-novels', 'marvel', 'graphic-novel', 'superheroes', 'comics-graphic-novels', 'young-adult', 'comic-books', 'marvel-comics', 'lgbt', 'ya', 'superhero', 'lgbtq', 'fiction', 'comics-and-graphic-novels', 'books-i-own', 'fantasy', 'read-in-2014', 'graphic-novels-comics', 'comic', 'read-in-2015', 'avengers', 'marvel-now', 'read-in-2016', 'queer', 'lgbtqia', 'science-fiction', 'young-avengers', 'series', 'graphic-novels-and-comics', 'comics-read', 'sci-fi', 'comics-marvel', 'favourites', 'graphic', 'read-2016', '2015-reads', 'sequential-art', 'comics-manga', 'comic-book', 'glbt', 'read-2014', 'adventure', 'read-comics', '2016-reads', 'marvel-unlimited', 'lgbt-characters', 'manga-comics', 'contemporary', 'aliens', '5-stars', 'read-2015', 'comics-gn', 'magic', 'poc', 'english', 'teen', '2014-releases', 'comic-books-graphic-novels', 'romance', 'to-read-comics', 'read-in-2017', 'graphic-novels-read', 'library-books', 'wish-list', 'diversity', 'poc-characters', 'action', 'm-m', 'superhero-comics', 'super-heroes', 'read-in-english', 'comics-2014', 'queer-characters', 'comic-volumes', '3-stars', 'read-2017', 'lgbt-authors', 'diverse', 'type-comics', 'mythology', 'lgbtqa', 'diverse-books', 'comic-trades', 'graphic-novel-comic', '4-stars', 'comixology', '2014-reads', 'from-the-library', 'comics-to-read', 'trade-paperbacks', 'borrowed', 'comic-graphic-novel']

Original: ['to-read', 'mystery', 'cozy-mystery', 'cozy-mysteries', 'mysteries', 'fiction', 'currently-reading', 'series', 'cozy', 'julie-hyzy', 'mystery-cozy', 'food', 'cooking', 'washington-dc', 'cozies', 'library', 'adult', 'favorites', 'mystery-series', 'e-book', 'culinary-mystery', 'read-in-2015', 'culinary-mysteries', 'owned', 'murder-mystery', 'mystery-thriller', 'nook', 'kindle', 'contemporary', 'white-house-chef', 'default', 'part-of-a-series', 'hyzy-julie', 'culinary', 'paperback', 'mystery-suspense', 'white-house', 'holiday', 'crime', 'cosy-mysteries', 'read-in-2012', 'favorite-authors', 'foodie', 'read-2011', 'books-i-own', 'white-house-chef-mysteries', 'read-in-2009', 'food-related', 'books-read-in-2017', 'food-and-drink', 'adult-fiction', 'christmas', 'humour', 'cooking-mystery', 'read-2015', 'need-to-get', 'j-author', 'h-title', 'h-author', 'white-house-chef-series', 'ebook', 'wish-list', 'h', 'author-h', 'read-2013', 'hyzy', 'detective', 'books', 'gr-authors', 'books-read-2013', 'romance', 'cozy-foodie', 'crime-mystery', 'read-2012', 'mystery-read', 'cooking-food', 'mysteries-and-thrillers', 'general', 'chick-lit', 'read-in-2011', 'h-authors', 'books-for-review', 'mystery-and-suspense', 'next-in-a-series', 'e-books-to-read', 'read-2009', 'white-house-chef-mystery']
Cleaned:  ['mystery', 'cozy-mystery', 'cozy-mysteries', 'mysteries', 'fiction', 'series', 'cozy', 'julie-hyzy', 'mystery-cozy', 'food', 'cooking', 'washington-dc', 'cozies', 'adult', 'mystery-series', 'e-book', 'culinary-mystery', 'read-in-2015', 'culinary-mysteries', 'murder-mystery', 'mystery-thriller', 'nook', 'contemporary', 'white-house-chef', 'part-of-a-series', 'hyzy-julie', 'culinary', 'paperback', 'mystery-suspense', 'white-house', 'holiday', 'crime', 'cosy-mysteries', 'read-in-2012', 'favorite-authors', 'foodie', 'read-2011', 'books-i-own', 'white-house-chef-mysteries', 'read-in-2009', 'food-related', 'books-read-in-2017', 'food-and-drink', 'adult-fiction', 'christmas', 'humour', 'cooking-mystery', 'read-2015', 'need-to-get', 'j-author', 'h-title', 'h-author', 'white-house-chef-series', 'wish-list', 'h', 'author-h', 'read-2013', 'hyzy', 'detective', 'books', 'gr-authors', 'books-read-2013', 'romance', 'cozy-foodie', 'crime-mystery', 'read-2012', 'mystery-read', 'cooking-food', 'mysteries-and-thrillers', 'general', 'chick-lit', 'read-in-2011', 'h-authors', 'books-for-review', 'mystery-and-suspense', 'next-in-a-series', 'e-books-to-read', 'read-2009', 'white-house-chef-mystery']

Original: ['to-read', 'horror', 'fiction', 'favorites', 'currently-reading', 'classics', 'gothic', 'mystery', 'book-club', 'classic', 'books-i-own', 'audiobook', 'owned', 'favourites', 'to-buy', 'audiobooks', 'library', 'adult', 'audio', 'adult-fiction', 'read-in-2017', 'novels', 'read-in-2016', 'kindle', 'literature', 'american', 'wish-list', 'thriller', 'read-in-2015', '20th-century', 'suspense', 'ebook', 'dark', 'literary-fiction', 'creepy', 'young-adult', 'american-literature', 'fantasy', 'modern-classics', 'read-in-2014', 'mystery-thriller', 'read-2017', 'owned-books', 'read-2016', 'spooky', 'female-authors', 'family', 'halloween', 'audible', 'shirley-jackson', 'audio-books', '1960s', 'female-author', 'unreliable-narrator', 'novel', 'read-2015', 'ebooks', 'general-fiction', 'mental-illness', 'library-books', 'read-in-2013', 'short-novels', 'read-in-2011', 'maybe', 'short-stories', 'crime', 'ya', 'mystery-suspense', 'audio-book', 'gothic-horror', 'bookclub', 'all-time-favorites', 'read-2014', 'american-lit', 'borrowed', 'women-writers', 'women', 'read-in-english', 'favorite-books', 'gothic-fiction', 'sisters', '2017-reads', 'usa', 'english', 'drama', 'novella', 'to-read-fiction', 'novellas', 'women-authors', 'horror-thriller', '2016-reads', '2016-reading-challenge', 'e-books', 'weird', 'short', '5-stars', 'terror', 'read-in-2012', 'scary', 'contemporary']
Cleaned:  ['horror', 'fiction', 'classics', 'gothic', 'mystery', 'book-club', 'classic', 'books-i-own', 'favourites', 'to-buy', 'audiobooks', 'adult', 'adult-fiction', 'read-in-2017', 'novels', 'read-in-2016', 'literature', 'american', 'wish-list', 'thriller', 'read-in-2015', '20th-century', 'suspense', 'dark', 'literary-fiction', 'creepy', 'young-adult', 'american-literature', 'fantasy', 'modern-classics', 'read-in-2014', 'mystery-thriller', 'read-2017', 'owned-books', 'read-2016', 'spooky', 'female-authors', 'family', 'halloween', 'audible', 'shirley-jackson', 'audio-books', '1960s', 'female-author', 'unreliable-narrator', 'novel', 'read-2015', 'ebooks', 'general-fiction', 'mental-illness', 'library-books', 'read-in-2013', 'short-novels', 'read-in-2011', 'maybe', 'short-stories', 'crime', 'ya', 'mystery-suspense', 'audio-book', 'gothic-horror', 'bookclub', 'all-time-favorites', 'read-2014', 'american-lit', 'borrowed', 'women-writers', 'women', 'read-in-english', 'favorite-books', 'gothic-fiction', 'sisters', '2017-reads', 'usa', 'english', 'drama', 'novella', 'to-read-fiction', 'novellas', 'women-authors', 'horror-thriller', '2016-reads', '2016-reading-challenge', 'e-books', 'weird', 'short', '5-stars', 'terror', 'read-in-2012', 'scary', 'contemporary']

Original: ['to-read', 'favorites', 'romance', 'currently-reading', 'kristen-ashley', 'erotica', 'contemporary-romance', 'bdsm', 'contemporary', 'alpha-male', 'series', 'kindle', 'adult', 'erotic-romance', 'dnf', 'alpha-males', 'erotic', 'alpha', 'bad-boys', 'ebook', 'favourites', 'bad-boy', 're-read', 'steamy', 'ka', 'anti-hero', 'favorite', '5-stars', 'read-in-2012', 'audible', 'new-adult', 'chick-lit', 'fiction', 'ebooks', 'hot', 'dark', 'read-in-2013', '4-stars', 'audiobook', 'adult-romance', 'm-f', 'owned', 'romance-contemporary', 'alpha-hero', 'e-book', 'part-of-a-series', 'favorite-authors', 'dirty-talk', 'first-in-series', 'did-not-finish', 'books-i-own', 'read-in-2014', 'billionaire', 'faves', 'drama', 're-reads', 'all-time-favorites', 'audio', 'mafia', '5-star', 'smut', 'reread', 'favorite-author', 'nook', 'read-2012', 'read-2013', 'favs', 'sexy', 'hot-hot-hot', 'audiobooks', 'kindle-books', 'author-kristen-ashley', 'read-in-2015', 'insta-love', 'hea', 'dirty-talker', 'book-boyfriends', 'lendable', 'favorite-series', 'maybe', 'ashley-kristen', '2013-reads', 'adult-fiction', 'alphas', '2012-reads', 'book-boyfriend', 'crime', 'read-2014', 'owned-books', 'guilty-pleasures', 'possessive', 'e-books', 'kristen-ashley-books', 'favorite-books', '3-stars', 'unfinished-hero', 'dark-romance', 'reviewed', 'read-in-2017', 'audio-book']
Cleaned:  ['romance', 'kristen-ashley', 'erotica', 'contemporary-romance', 'bdsm', 'contemporary', 'alpha-male', 'series', 'adult', 'erotic-romance', 'dnf', 'alpha-males', 'erotic', 'alpha', 'bad-boys', 'favourites', 'bad-boy', 're-read', 'steamy', 'ka', 'anti-hero', 'favorite', '5-stars', 'read-in-2012', 'audible', 'new-adult', 'chick-lit', 'fiction', 'ebooks', 'hot', 'dark', 'read-in-2013', '4-stars', 'adult-romance', 'm-f', 'romance-contemporary', 'alpha-hero', 'e-book', 'part-of-a-series', 'favorite-authors', 'dirty-talk', 'first-in-series', 'did-not-finish', 'books-i-own', 'read-in-2014', 'billionaire', 'faves', 'drama', 're-reads', 'all-time-favorites', 'mafia', '5-star', 'smut', 'reread', 'favorite-author', 'nook', 'read-2012', 'read-2013', 'favs', 'sexy', 'hot-hot-hot', 'audiobooks', 'kindle-books', 'author-kristen-ashley', 'read-in-2015', 'insta-love', 'hea', 'dirty-talker', 'book-boyfriends', 'lendable', 'favorite-series', 'maybe', 'ashley-kristen', '2013-reads', 'adult-fiction', 'alphas', '2012-reads', 'book-boyfriend', 'crime', 'read-2014', 'owned-books', 'guilty-pleasures', 'possessive', 'e-books', 'kristen-ashley-books', 'favorite-books', '3-stars', 'unfinished-hero', 'dark-romance', 'reviewed', 'read-in-2017', 'audio-book']

Total unique cleaned genre tags found: 87921
Top 20 most frequent cleaned genre tags:
- fiction: 61014
- books-i-own: 56795
- to-buy: 47894
- ebooks: 47335
- wish-list: 44869
- owned-books: 44340
- romance: 43417
- series: 39949
- contemporary: 39246
- adult: 37455
- audiobooks: 34514
- e-book: 33619
- favourites: 31801
- read-in-2016: 31398
- read-in-2015: 31149
- fantasy: 30771
- i-own: 29345
- dnf: 28616
- maybe: 28591
- young-adult: 28424

In [ ]:
df.head()

,user_id,book_id,is_read,rating,date_added,date_updated,read_at,started_at,reading_duration_days,title,...,average_rating,publication_year,description,genres,num_pages,original_title,original_publication_year,target,genres_list,cleaned_genres
0,6ae8a47b5a7f8b0b145cf597a5d5c929,17342700,1,5,2016-12-21 11:23:08,2017-04-24 19:20:25,2017-04-24 00:00:00,2017-04-22,2.0,"Gathering Darkness (Falling Kingdoms, #3)",...,4.32,2014.0,"In GATHERING DARKNESS, book three of the New Y...",['to-read' 'young-adult' 'currently-reading' '...,416,Gathering Darkness,2014.0,0.0,"[to-read, young-adult, currently-reading, fant...","[young-adult, fantasy, books-i-own, ya, magic,..."
1,0c7429f150417a1af3c7045fc89a3f4e,18513581,1,3,2016-07-23 07:06:57,2017-01-01 17:40:35,2016-12-10 00:00:00,2016-12-02,8.0,"Young Avengers, Volume 2: Alternative Culture",...,4.18,2014.0,Ever wonder what the super hero equivalent of ...,['to-read' 'comics' 'graphic-novels' 'marvel' ...,112,"Young Avengers, Volume 2: Alternative Culture",2014.0,0.0,"[to-read, comics, graphic-novels, marvel, grap...","[comics, graphic-novels, marvel, graphic-novel..."
2,cd75b15c85a3dd27fef5ec3403a5f873,3993755,1,0,2017-06-30 08:33:08,2017-06-30 08:33:26,2017-06-30 08:33:26,2017-06-29,1.0,"Hail to the Chef (A White House Chef Mystery, #2)",...,3.98,2008.0,White House executive chef Ollie Paras has to ...,['to-read' 'mystery' 'cozy-mystery' 'cozy-myst...,328,"Hail to the Chef (White House Chef Mystery, Bo...",2008.0,NaN,"[to-read, mystery, cozy-mystery, cozy-mysterie...","[mystery, cozy-mystery, cozy-mysteries, myster..."
3,86b931f21144e8d743b40dc26f82073c,89724,1,4,2011-10-07 13:43:08,2011-11-03 20:05:41,2011-10-13 00:00:00,2011-10-07,6.0,We Have Always Lived in the Castle,...,4.04,2006.0,Merricat Blackwood lives on the family estate ...,['to-read' 'horror' 'fiction' 'favorites' 'cur...,146,We Have Always Lived in the Castle,1962.0,1.0,"[to-read, horror, fiction, favorites, currentl...","[horror, fiction, classics, gothic, mystery, b..."
4,9adddbae754bf26fb04999a0f79f14c4,13565914,1,3,2013-01-03 18:42:59,2013-01-03 18:51:59,2013-01-04 18:51:59,2013-01-01,3.0,"Knight (Unfinished Hero, #1)",...,3.94,2012.0,Anya Gage has learned that to get anything goo...,['to-read' 'favorites' 'romance' 'currently-re...,285,Knight,2012.0,1.0,"[to-read, favorites, romance, currently-readin...","[romance, kristen-ashley, erotica, contemporar..."

In [ ]:
## Normalize Synonymous Tags

# Genre tags often have variations or synonyms (e.g., 'sci-fi' and 'science-fiction'). This step aims to consolidate these into a single, standardized tag to improve consistency and reduce dimensionality.

In [56]:
from itertools import chain
from collections import defaultdict

# Display top 50 most frequent cleaned genre tags to help identify synonyms
all_cleaned_tags = defaultdict(int)
for tag in chain.from_iterable(df['cleaned_genres']):
    all_cleaned_tags[tag] += 1

print("Top 50 most frequent cleaned genre tags (to identify synonyms):")
for tag, count in sorted(all_cleaned_tags.items(), key=lambda item: item[1], reverse=True)[:50]:
    print(f"- {tag}: {count}")

Top 50 most frequent cleaned genre tags (to identify synonyms):
- fiction: 61014
- books-i-own: 56795
- to-buy: 47894
- ebooks: 47335
- wish-list: 44869
- owned-books: 44340
- romance: 43417
- series: 39949
- contemporary: 39246
- adult: 37455
- audiobooks: 34514
- e-book: 33619
- favourites: 31801
- read-in-2016: 31398
- read-in-2015: 31149
- fantasy: 30771
- i-own: 29345
- dnf: 28616
- maybe: 28591
- young-adult: 28424
- e-books: 27701
- read-in-2014: 27643
- read-in-2017: 26428
- mystery: 25044
- did-not-finish: 24945
- ya: 24137
- my-library: 23980
- read-in-2013: 23277
- adult-fiction: 22507
- own-it: 22388
- reviewed: 22309
- novels: 21400
- book-club: 21123
- audible: 21012
- abandoned: 20869
- read-2015: 20834
- read-2016: 20362
- books: 20286
- arc: 19321
- adventure: 19290
- paranormal: 19199
- tbr: 19052
- audio-books: 19039
- 4-stars: 18802
- read-2014: 18411
- have: 18358
- 5-stars: 18071
- audio-book: 17762
- read-in-2012: 17510
- favorite: 17041

Based on the frequent tags, here are some common synonyms I've identified that we should normalize. You can expand this list as needed for more comprehensive normalization.

For example:
*   `sci-fi` and `science-fiction` can be normalized to `science fiction`
*   `ya` and `young-adult` can be normalized to `young adult`
*   `fantasy-romance` and `paranormal-romance` might be normalized to `fantasy romance` and `paranormal romance` respectively, or even a broader `romance` category depending on the desired granularity.

In [58]:
# Define a mapping for synonymous tags
synonym_map = {
    'sci-fi': 'science fiction',
    'science-fiction': 'science fiction',
    'ya': 'young adult',
    'young-adult': 'young adult',
    'romance-fantasy': 'fantasy romance',
    'fantasy-romance': 'fantasy romance',
    'paranormal-romance': 'paranormal romance',
    'historical-fiction': 'historical fiction',
    'mystery-thriller': 'mystery thriller',
    'thriller-mystery': 'mystery thriller',
    'graphic-novels': 'graphic novel',
    'graphic-novel': 'graphic novel',
    'comics': 'graphic novel',
    'middle-grade': 'middle grade',
    'urban-fantasy': 'urban fantasy',
    'contemporary-romance': 'contemporary romance',
    'dark-fantasy': 'dark fantasy',
    'high-fantasy': 'high fantasy',
    'epic-fantasy': 'epic fantasy',
    'magical-realism': 'magical realism',
    'dystopian': 'dystopia',
    'post-apocalyptic': 'post apocalyptic',
    'lgbt': 'lgbtq',
    'glbt': 'lgbtq',
    'lgbtqia': 'lgbtq'
}

def normalize_tags(genre_list, mapping):
    normalized = []
    for tag in genre_list:
        # Convert tag to lowercase for case-insensitive matching
        lower_tag = tag.lower()
        # Apply mapping, default to original tag if no synonym found
        normalized_tag = mapping.get(lower_tag, lower_tag)
        normalized.append(normalized_tag)
    return normalized

# Apply the normalization to the cleaned_genres column
df['normalized_genres'] = df['cleaned_genres'].apply(lambda x: normalize_tags(x, synonym_map))

print("Sample of cleaned genres and normalized genres:")
for i in range(5):
    print(f"Cleaned:    {df['cleaned_genres'].iloc[i]}")
    print(f"Normalized: {df['normalized_genres'].iloc[i]}\n")

Sample of cleaned genres and normalized genres:
Cleaned:    ['young-adult', 'fantasy', 'books-i-own', 'ya', 'magic', 'romance', 'series', 'ya-fantasy', 'to-buy', 'favourites', 'read-in-2016', 'read-in-2015', 'adventure', 'falling-kingdoms', 'read-2016', 'read-in-2017', 'fiction', '2014-releases', 'high-fantasy', 'wish-list', 'i-own', '2016-reads', '2015-reads', '5-stars', 'ebooks', 'owned-books', 'witches', 'royalty', 'audiobooks', 'tbr-pile', 'morgan-rhodes', 'epic-fantasy', '4-stars', 'need-to-buy', 'owned-tbr', '2014-release', 'read-in-english', 'love-triangle', 'favorite-books', 'paranormal', 'read-2017', '2017-reads', 'multiple-pov', 'ya-fiction', 'books-to-buy', 'must-read', 'e-books', 'favorite-series', 'unfinished-series', 'hardcover', 'young-adult-fantasy', '2017-tbr', 'all-time-favorites', 'favorite', 'tbr-owned', 'fantasy-romance', 'teen', 'book-boyfriends', 'cover-love', 'series-to-finish', 'want-to-own', 'want-to-buy', 'tbr', 'english', '2015-favorites', 'medieval', 'action', 'book-boyfriend', 'cliffhanger', 'my-bookshelf', 'own-to-read', '2016-read', 'on-my-bookshelf', 'war', 'on-my-shelves', 'bought', 'signed', 'beautiful-covers', 'sci-fi-fantasy', 'assassins', 'reviewed', 'otp', 'read-in-2014', 'fantasy-magic', 'kingdoms', 'lgbt', 'books-i-have', 'dnf', 'have']
Normalized: ['young adult', 'fantasy', 'books-i-own', 'young adult', 'magic', 'romance', 'series', 'ya-fantasy', 'to-buy', 'favourites', 'read-in-2016', 'read-in-2015', 'adventure', 'falling-kingdoms', 'read-2016', 'read-in-2017', 'fiction', '2014-releases', 'high fantasy', 'wish-list', 'i-own', '2016-reads', '2015-reads', '5-stars', 'ebooks', 'owned-books', 'witches', 'royalty', 'audiobooks', 'tbr-pile', 'morgan-rhodes', 'epic fantasy', '4-stars', 'need-to-buy', 'owned-tbr', '2014-release', 'read-in-english', 'love-triangle', 'favorite-books', 'paranormal', 'read-2017', '2017-reads', 'multiple-pov', 'ya-fiction', 'books-to-buy', 'must-read', 'e-books', 'favorite-series', 'unfinished-series', 'hardcover', 'young-adult-fantasy', '2017-tbr', 'all-time-favorites', 'favorite', 'tbr-owned', 'fantasy romance', 'teen', 'book-boyfriends', 'cover-love', 'series-to-finish', 'want-to-own', 'want-to-buy', 'tbr', 'english', '2015-favorites', 'medieval', 'action', 'book-boyfriend', 'cliffhanger', 'my-bookshelf', 'own-to-read', '2016-read', 'on-my-bookshelf', 'war', 'on-my-shelves', 'bought', 'signed', 'beautiful-covers', 'sci-fi-fantasy', 'assassins', 'reviewed', 'otp', 'read-in-2014', 'fantasy-magic', 'kingdoms', 'lgbtq', 'books-i-have', 'dnf', 'have']

Cleaned:    ['comics', 'graphic-novels', 'marvel', 'graphic-novel', 'superheroes', 'comics-graphic-novels', 'young-adult', 'comic-books', 'marvel-comics', 'lgbt', 'ya', 'superhero', 'lgbtq', 'fiction', 'comics-and-graphic-novels', 'books-i-own', 'fantasy', 'read-in-2014', 'graphic-novels-comics', 'comic', 'read-in-2015', 'avengers', 'marvel-now', 'read-in-2016', 'queer', 'lgbtqia', 'science-fiction', 'young-avengers', 'series', 'graphic-novels-and-comics', 'comics-read', 'sci-fi', 'comics-marvel', 'favourites', 'graphic', 'read-2016', '2015-reads', 'sequential-art', 'comics-manga', 'comic-book', 'glbt', 'read-2014', 'adventure', 'read-comics', '2016-reads', 'marvel-unlimited', 'lgbt-characters', 'manga-comics', 'contemporary', 'aliens', '5-stars', 'read-2015', 'comics-gn', 'magic', 'poc', 'english', 'teen', '2014-releases', 'comic-books-graphic-novels', 'romance', 'to-read-comics', 'read-in-2017', 'graphic-novels-read', 'library-books', 'wish-list', 'diversity', 'poc-characters', 'action', 'm-m', 'superhero-comics', 'super-heroes', 'read-in-english', 'comics-2014', 'queer-characters', 'comic-volumes', '3-stars', 'read-2017', 'lgbt-authors', 'diverse', 'type-comics', 'mythology', 'lgbtqa', 'diverse-books', 'comic-trades', 'graphic-novel-comic', '4-stars', 'comixology', '2014-reads', 'from-the-library', 'comics-to-read', 'trade-paperbacks', 'borrowed', 'comic-graphic-novel']
Normalized: ['graphic novel', 'graphic novel', 'marvel', 'graphic novel', 'superheroes', 'comics-graphic-novels', 'young adult', 'comic-books', 'marvel-comics', 'lgbtq', 'young adult', 'superhero', 'lgbtq', 'fiction', 'comics-and-graphic-novels', 'books-i-own', 'fantasy', 'read-in-2014', 'graphic-novels-comics', 'comic', 'read-in-2015', 'avengers', 'marvel-now', 'read-in-2016', 'queer', 'lgbtq', 'science fiction', 'young-avengers', 'series', 'graphic-novels-and-comics', 'comics-read', 'science fiction', 'comics-marvel', 'favourites', 'graphic', 'read-2016', '2015-reads', 'sequential-art', 'comics-manga', 'comic-book', 'lgbtq', 'read-2014', 'adventure', 'read-comics', '2016-reads', 'marvel-unlimited', 'lgbt-characters', 'manga-comics', 'contemporary', 'aliens', '5-stars', 'read-2015', 'comics-gn', 'magic', 'poc', 'english', 'teen', '2014-releases', 'comic-books-graphic-novels', 'romance', 'to-read-comics', 'read-in-2017', 'graphic-novels-read', 'library-books', 'wish-list', 'diversity', 'poc-characters', 'action', 'm-m', 'superhero-comics', 'super-heroes', 'read-in-english', 'comics-2014', 'queer-characters', 'comic-volumes', '3-stars', 'read-2017', 'lgbt-authors', 'diverse', 'type-comics', 'mythology', 'lgbtqa', 'diverse-books', 'comic-trades', 'graphic-novel-comic', '4-stars', 'comixology', '2014-reads', 'from-the-library', 'comics-to-read', 'trade-paperbacks', 'borrowed', 'comic-graphic-novel']

Cleaned:    ['mystery', 'cozy-mystery', 'cozy-mysteries', 'mysteries', 'fiction', 'series', 'cozy', 'julie-hyzy', 'mystery-cozy', 'food', 'cooking', 'washington-dc', 'cozies', 'adult', 'mystery-series', 'e-book', 'culinary-mystery', 'read-in-2015', 'culinary-mysteries', 'murder-mystery', 'mystery-thriller', 'nook', 'contemporary', 'white-house-chef', 'part-of-a-series', 'hyzy-julie', 'culinary', 'paperback', 'mystery-suspense', 'white-house', 'holiday', 'crime', 'cosy-mysteries', 'read-in-2012', 'favorite-authors', 'foodie', 'read-2011', 'books-i-own', 'white-house-chef-mysteries', 'read-in-2009', 'food-related', 'books-read-in-2017', 'food-and-drink', 'adult-fiction', 'christmas', 'humour', 'cooking-mystery', 'read-2015', 'need-to-get', 'j-author', 'h-title', 'h-author', 'white-house-chef-series', 'wish-list', 'h', 'author-h', 'read-2013', 'hyzy', 'detective', 'books', 'gr-authors', 'books-read-2013', 'romance', 'cozy-foodie', 'crime-mystery', 'read-2012', 'mystery-read', 'cooking-food', 'mysteries-and-thrillers', 'general', 'chick-lit', 'read-in-2011', 'h-authors', 'books-for-review', 'mystery-and-suspense', 'next-in-a-series', 'e-books-to-read', 'read-2009', 'white-house-chef-mystery']
Normalized: ['mystery', 'cozy-mystery', 'cozy-mysteries', 'mysteries', 'fiction', 'series', 'cozy', 'julie-hyzy', 'mystery-cozy', 'food', 'cooking', 'washington-dc', 'cozies', 'adult', 'mystery-series', 'e-book', 'culinary-mystery', 'read-in-2015', 'culinary-mysteries', 'murder-mystery', 'mystery thriller', 'nook', 'contemporary', 'white-house-chef', 'part-of-a-series', 'hyzy-julie', 'culinary', 'paperback', 'mystery-suspense', 'white-house', 'holiday', 'crime', 'cosy-mysteries', 'read-in-2012', 'favorite-authors', 'foodie', 'read-2011', 'books-i-own', 'white-house-chef-mysteries', 'read-in-2009', 'food-related', 'books-read-in-2017', 'food-and-drink', 'adult-fiction', 'christmas', 'humour', 'cooking-mystery', 'read-2015', 'need-to-get', 'j-author', 'h-title', 'h-author', 'white-house-chef-series', 'wish-list', 'h', 'author-h', 'read-2013', 'hyzy', 'detective', 'books', 'gr-authors', 'books-read-2013', 'romance', 'cozy-foodie', 'crime-mystery', 'read-2012', 'mystery-read', 'cooking-food', 'mysteries-and-thrillers', 'general', 'chick-lit', 'read-in-2011', 'h-authors', 'books-for-review', 'mystery-and-suspense', 'next-in-a-series', 'e-books-to-read', 'read-2009', 'white-house-chef-mystery']

Cleaned:    ['horror', 'fiction', 'classics', 'gothic', 'mystery', 'book-club', 'classic', 'books-i-own', 'favourites', 'to-buy', 'audiobooks', 'adult', 'adult-fiction', 'read-in-2017', 'novels', 'read-in-2016', 'literature', 'american', 'wish-list', 'thriller', 'read-in-2015', '20th-century', 'suspense', 'dark', 'literary-fiction', 'creepy', 'young-adult', 'american-literature', 'fantasy', 'modern-classics', 'read-in-2014', 'mystery-thriller', 'read-2017', 'owned-books', 'read-2016', 'spooky', 'female-authors', 'family', 'halloween', 'audible', 'shirley-jackson', 'audio-books', '1960s', 'female-author', 'unreliable-narrator', 'novel', 'read-2015', 'ebooks', 'general-fiction', 'mental-illness', 'library-books', 'read-in-2013', 'short-novels', 'read-in-2011', 'maybe', 'short-stories', 'crime', 'ya', 'mystery-suspense', 'audio-book', 'gothic-horror', 'bookclub', 'all-time-favorites', 'read-2014', 'american-lit', 'borrowed', 'women-writers', 'women', 'read-in-english', 'favorite-books', 'gothic-fiction', 'sisters', '2017-reads', 'usa', 'english', 'drama', 'novella', 'to-read-fiction', 'novellas', 'women-authors', 'horror-thriller', '2016-reads', '2016-reading-challenge', 'e-books', 'weird', 'short', '5-stars', 'terror', 'read-in-2012', 'scary', 'contemporary']
Normalized: ['horror', 'fiction', 'classics', 'gothic', 'mystery', 'book-club', 'classic', 'books-i-own', 'favourites', 'to-buy', 'audiobooks', 'adult', 'adult-fiction', 'read-in-2017', 'novels', 'read-in-2016', 'literature', 'american', 'wish-list', 'thriller', 'read-in-2015', '20th-century', 'suspense', 'dark', 'literary-fiction', 'creepy', 'young adult', 'american-literature', 'fantasy', 'modern-classics', 'read-in-2014', 'mystery thriller', 'read-2017', 'owned-books', 'read-2016', 'spooky', 'female-authors', 'family', 'halloween', 'audible', 'shirley-jackson', 'audio-books', '1960s', 'female-author', 'unreliable-narrator', 'novel', 'read-2015', 'ebooks', 'general-fiction', 'mental-illness', 'library-books', 'read-in-2013', 'short-novels', 'read-in-2011', 'maybe', 'short-stories', 'crime', 'young adult', 'mystery-suspense', 'audio-book', 'gothic-horror', 'bookclub', 'all-time-favorites', 'read-2014', 'american-lit', 'borrowed', 'women-writers', 'women', 'read-in-english', 'favorite-books', 'gothic-fiction', 'sisters', '2017-reads', 'usa', 'english', 'drama', 'novella', 'to-read-fiction', 'novellas', 'women-authors', 'horror-thriller', '2016-reads', '2016-reading-challenge', 'e-books', 'weird', 'short', '5-stars', 'terror', 'read-in-2012', 'scary', 'contemporary']

Cleaned:    ['romance', 'kristen-ashley', 'erotica', 'contemporary-romance', 'bdsm', 'contemporary', 'alpha-male', 'series', 'adult', 'erotic-romance', 'dnf', 'alpha-males', 'erotic', 'alpha', 'bad-boys', 'favourites', 'bad-boy', 're-read', 'steamy', 'ka', 'anti-hero', 'favorite', '5-stars', 'read-in-2012', 'audible', 'new-adult', 'chick-lit', 'fiction', 'ebooks', 'hot', 'dark', 'read-in-2013', '4-stars', 'adult-romance', 'm-f', 'romance-contemporary', 'alpha-hero', 'e-book', 'part-of-a-series', 'favorite-authors', 'dirty-talk', 'first-in-series', 'did-not-finish', 'books-i-own', 'read-in-2014', 'billionaire', 'faves', 'drama', 're-reads', 'all-time-favorites', 'mafia', '5-star', 'smut', 'reread', 'favorite-author', 'nook', 'read-2012', 'read-2013', 'favs', 'sexy', 'hot-hot-hot', 'audiobooks', 'kindle-books', 'author-kristen-ashley', 'read-in-2015', 'insta-love', 'hea', 'dirty-talker', 'book-boyfriends', 'lendable', 'favorite-series', 'maybe', 'ashley-kristen', '2013-reads', 'adult-fiction', 'alphas', '2012-reads', 'book-boyfriend', 'crime', 'read-2014', 'owned-books', 'guilty-pleasures', 'possessive', 'e-books', 'kristen-ashley-books', 'favorite-books', '3-stars', 'unfinished-hero', 'dark-romance', 'reviewed', 'read-in-2017', 'audio-book']
Normalized: ['romance', 'kristen-ashley', 'erotica', 'contemporary romance', 'bdsm', 'contemporary', 'alpha-male', 'series', 'adult', 'erotic-romance', 'dnf', 'alpha-males', 'erotic', 'alpha', 'bad-boys', 'favourites', 'bad-boy', 're-read', 'steamy', 'ka', 'anti-hero', 'favorite', '5-stars', 'read-in-2012', 'audible', 'new-adult', 'chick-lit', 'fiction', 'ebooks', 'hot', 'dark', 'read-in-2013', '4-stars', 'adult-romance', 'm-f', 'romance-contemporary', 'alpha-hero', 'e-book', 'part-of-a-series', 'favorite-authors', 'dirty-talk', 'first-in-series', 'did-not-finish', 'books-i-own', 'read-in-2014', 'billionaire', 'faves', 'drama', 're-reads', 'all-time-favorites', 'mafia', '5-star', 'smut', 'reread', 'favorite-author', 'nook', 'read-2012', 'read-2013', 'favs', 'sexy', 'hot-hot-hot', 'audiobooks', 'kindle-books', 'author-kristen-ashley', 'read-in-2015', 'insta-love', 'hea', 'dirty-talker', 'book-boyfriends', 'lendable', 'favorite-series', 'maybe', 'ashley-kristen', '2013-reads', 'adult-fiction', 'alphas', '2012-reads', 'book-boyfriend', 'crime', 'read-2014', 'owned-books', 'guilty-pleasures', 'possessive', 'e-books', 'kristen-ashley-books', 'favorite-books', '3-stars', 'unfinished-hero', 'dark-romance', 'reviewed', 'read-in-2017', 'audio-book']

In [60]:
from itertools import chain
from collections import defaultdict

# Recalculate and display the top 20 most frequent normalized genre tags
all_normalized_tags = defaultdict(int)
for tag in chain.from_iterable(df['normalized_genres']):
    all_normalized_tags[tag] += 1

print(f"Total unique normalized genre tags found: {len(all_normalized_tags)}")
print("Top 20 most frequent normalized genre tags:")
for tag, count in sorted(all_normalized_tags.items(), key=lambda item: item[1], reverse=True)[:20]:
    print(f"- {tag}: {count}")

Total unique normalized genre tags found: 87884
Top 20 most frequent normalized genre tags:
- fiction: 61014
- books-i-own: 56795
- young adult: 52561
- to-buy: 47894
- ebooks: 47335
- wish-list: 44869
- owned-books: 44340
- romance: 43417
- series: 39949
- contemporary: 39246
- adult: 37455
- audiobooks: 34514
- e-book: 33619
- favourites: 31801
- read-in-2016: 31398
- read-in-2015: 31149
- fantasy: 30771
- i-own: 29345
- dnf: 28616
- maybe: 28591

## Map to Canonical Genres

After normalizing synonymous tags, the next step is to map the refined genre tags to a predefined set of canonical (standardized) genres. This further reduces dimensionality and ensures consistency across the dataset, making the genre data more manageable for analysis or machine learning tasks.

In [61]:
import collections
# Define a mapping from normalized tags to broader, canonical genres (or multiple canonical genres)
# Keys are lowercased normalized tags, values are lists of canonical genre strings (Title Cased)
# This map is designed to be less aggressive in collapsing genres.
canonical_genre_map = {
    'fiction': ['Fiction'],
    'fantasy': ['Fantasy'],
    'science fiction': ['Science Fiction'],
    'young adult': ['Young Adult'],
    'romance': ['Romance'],
    'mystery thriller': ['Mystery & Thriller'],
    'historical fiction': ['Historical Fiction'],
    'graphic novel': ['Graphic Novel'],
    'horror': ['Horror'],
    'biography': ['Biography & Memoir'],
    'memoir': ['Biography & Memoir'],
    'nonfiction': ['Non-Fiction'],
    'contemporary': ['Contemporary'],
    'adventure': ['Adventure'],

    # Split out specific sub-genres or map to multiple broader categories
    'dystopia': ['Science Fiction', 'Dystopia'],
    'urban fantasy': ['Fantasy', 'Urban Fantasy'],
    'high fantasy': ['Fantasy'],
    'epic fantasy': ['Fantasy'],
    'paranormal romance': ['Romance', 'Paranormal Romance'],
    'fantasy romance': ['Fantasy', 'Romance'],
    'lgbtq': ['LGBTQ+'],
    'historical romance': ['Historical Fiction', 'Romance'],
    'thriller': ['Mystery & Thriller'],
    'mystery': ['Mystery & Thriller'],
    'crime': ['Mystery & Thriller'],
    'literary fiction': ['Fiction', 'Literary Fiction'],
    'middle grade': ['Middle Grade'],
    'classic': ['Classics'],
    'classics': ['Classics'],
    'adult fiction': ['Fiction'],
    'magical realism': ['Fantasy', 'Magical Realism'],

    # Additional common genre tags that should be canonical
    'superhero': ['Superhero'],
    'action': ['Action'],
    'magic': ['Fantasy'],
    'western': ['Western'],
    'paranormal': ['Paranormal'],
    'erotica': ['Erotica'],
    'dark fantasy': ['Fantasy', 'Dark Fantasy'],
    'post apocalyptic': ['Science Fiction', 'Post-Apocalyptic'],
    'steampunk': ['Science Fiction', 'Fantasy', 'Steampunk'],

    # Ensure other variants of LGBTQ+ are covered if they didn't get normalized before
    'lgbt': ['LGBTQ+'],
    'glbt': ['LGBTQ+'],
    'lgbtqia': ['LGBTQ+'],
    'teen': ['Young Adult'],
}

def map_to_canonical_genres(normalized_genre_list, mapping):
    canonical = set()
    for tag in normalized_genre_list:
        mapped_genres = mapping.get(tag, None)
        if mapped_genres:
            canonical.update(mapped_genres)
        # If a normalized tag is not explicitly mapped, it is excluded from canonical.
        # This keeps the canonical list strictly to defined broader categories.
    return list(canonical) if canonical else []

# Apply the mapping to create a new 'canonical_genres' column
df['canonical_genres'] = df['normalized_genres'].apply(lambda x: map_to_canonical_genres(x, canonical_genre_map))

print("Sample of normalized genres and refined canonical genres:")
for i in range(5):
    print(f"Normalized: {df['normalized_genres'].iloc[i]}")
    print(f"Canonical:  {df['canonical_genres'].iloc[i]}\n")

Sample of normalized genres and refined canonical genres:
Normalized: ['young adult', 'fantasy', 'books-i-own', 'young adult', 'magic', 'romance', 'series', 'ya-fantasy', 'to-buy', 'favourites', 'read-in-2016', 'read-in-2015', 'adventure', 'falling-kingdoms', 'read-2016', 'read-in-2017', 'fiction', '2014-releases', 'high fantasy', 'wish-list', 'i-own', '2016-reads', '2015-reads', '5-stars', 'ebooks', 'owned-books', 'witches', 'royalty', 'audiobooks', 'tbr-pile', 'morgan-rhodes', 'epic fantasy', '4-stars', 'need-to-buy', 'owned-tbr', '2014-release', 'read-in-english', 'love-triangle', 'favorite-books', 'paranormal', 'read-2017', '2017-reads', 'multiple-pov', 'ya-fiction', 'books-to-buy', 'must-read', 'e-books', 'favorite-series', 'unfinished-series', 'hardcover', 'young-adult-fantasy', '2017-tbr', 'all-time-favorites', 'favorite', 'tbr-owned', 'fantasy romance', 'teen', 'book-boyfriends', 'cover-love', 'series-to-finish', 'want-to-own', 'want-to-buy', 'tbr', 'english', '2015-favorites', 'medieval', 'action', 'book-boyfriend', 'cliffhanger', 'my-bookshelf', 'own-to-read', '2016-read', 'on-my-bookshelf', 'war', 'on-my-shelves', 'bought', 'signed', 'beautiful-covers', 'sci-fi-fantasy', 'assassins', 'reviewed', 'otp', 'read-in-2014', 'fantasy-magic', 'kingdoms', 'lgbtq', 'books-i-have', 'dnf', 'have']
Canonical:  ['Fiction', 'LGBTQ+', 'Romance', 'Fantasy', 'Young Adult', 'Action', 'Paranormal', 'Adventure']

Normalized: ['graphic novel', 'graphic novel', 'marvel', 'graphic novel', 'superheroes', 'comics-graphic-novels', 'young adult', 'comic-books', 'marvel-comics', 'lgbtq', 'young adult', 'superhero', 'lgbtq', 'fiction', 'comics-and-graphic-novels', 'books-i-own', 'fantasy', 'read-in-2014', 'graphic-novels-comics', 'comic', 'read-in-2015', 'avengers', 'marvel-now', 'read-in-2016', 'queer', 'lgbtq', 'science fiction', 'young-avengers', 'series', 'graphic-novels-and-comics', 'comics-read', 'science fiction', 'comics-marvel', 'favourites', 'graphic', 'read-2016', '2015-reads', 'sequential-art', 'comics-manga', 'comic-book', 'lgbtq', 'read-2014', 'adventure', 'read-comics', '2016-reads', 'marvel-unlimited', 'lgbt-characters', 'manga-comics', 'contemporary', 'aliens', '5-stars', 'read-2015', 'comics-gn', 'magic', 'poc', 'english', 'teen', '2014-releases', 'comic-books-graphic-novels', 'romance', 'to-read-comics', 'read-in-2017', 'graphic-novels-read', 'library-books', 'wish-list', 'diversity', 'poc-characters', 'action', 'm-m', 'superhero-comics', 'super-heroes', 'read-in-english', 'comics-2014', 'queer-characters', 'comic-volumes', '3-stars', 'read-2017', 'lgbt-authors', 'diverse', 'type-comics', 'mythology', 'lgbtqa', 'diverse-books', 'comic-trades', 'graphic-novel-comic', '4-stars', 'comixology', '2014-reads', 'from-the-library', 'comics-to-read', 'trade-paperbacks', 'borrowed', 'comic-graphic-novel']
Canonical:  ['Superhero', 'Science Fiction', 'Fiction', 'LGBTQ+', 'Contemporary', 'Romance', 'Fantasy', 'Young Adult', 'Action', 'Graphic Novel', 'Adventure']

Normalized: ['mystery', 'cozy-mystery', 'cozy-mysteries', 'mysteries', 'fiction', 'series', 'cozy', 'julie-hyzy', 'mystery-cozy', 'food', 'cooking', 'washington-dc', 'cozies', 'adult', 'mystery-series', 'e-book', 'culinary-mystery', 'read-in-2015', 'culinary-mysteries', 'murder-mystery', 'mystery thriller', 'nook', 'contemporary', 'white-house-chef', 'part-of-a-series', 'hyzy-julie', 'culinary', 'paperback', 'mystery-suspense', 'white-house', 'holiday', 'crime', 'cosy-mysteries', 'read-in-2012', 'favorite-authors', 'foodie', 'read-2011', 'books-i-own', 'white-house-chef-mysteries', 'read-in-2009', 'food-related', 'books-read-in-2017', 'food-and-drink', 'adult-fiction', 'christmas', 'humour', 'cooking-mystery', 'read-2015', 'need-to-get', 'j-author', 'h-title', 'h-author', 'white-house-chef-series', 'wish-list', 'h', 'author-h', 'read-2013', 'hyzy', 'detective', 'books', 'gr-authors', 'books-read-2013', 'romance', 'cozy-foodie', 'crime-mystery', 'read-2012', 'mystery-read', 'cooking-food', 'mysteries-and-thrillers', 'general', 'chick-lit', 'read-in-2011', 'h-authors', 'books-for-review', 'mystery-and-suspense', 'next-in-a-series', 'e-books-to-read', 'read-2009', 'white-house-chef-mystery']
Canonical:  ['Contemporary', 'Romance', 'Fiction', 'Mystery & Thriller']

Normalized: ['horror', 'fiction', 'classics', 'gothic', 'mystery', 'book-club', 'classic', 'books-i-own', 'favourites', 'to-buy', 'audiobooks', 'adult', 'adult-fiction', 'read-in-2017', 'novels', 'read-in-2016', 'literature', 'american', 'wish-list', 'thriller', 'read-in-2015', '20th-century', 'suspense', 'dark', 'literary-fiction', 'creepy', 'young adult', 'american-literature', 'fantasy', 'modern-classics', 'read-in-2014', 'mystery thriller', 'read-2017', 'owned-books', 'read-2016', 'spooky', 'female-authors', 'family', 'halloween', 'audible', 'shirley-jackson', 'audio-books', '1960s', 'female-author', 'unreliable-narrator', 'novel', 'read-2015', 'ebooks', 'general-fiction', 'mental-illness', 'library-books', 'read-in-2013', 'short-novels', 'read-in-2011', 'maybe', 'short-stories', 'crime', 'young adult', 'mystery-suspense', 'audio-book', 'gothic-horror', 'bookclub', 'all-time-favorites', 'read-2014', 'american-lit', 'borrowed', 'women-writers', 'women', 'read-in-english', 'favorite-books', 'gothic-fiction', 'sisters', '2017-reads', 'usa', 'english', 'drama', 'novella', 'to-read-fiction', 'novellas', 'women-authors', 'horror-thriller', '2016-reads', '2016-reading-challenge', 'e-books', 'weird', 'short', '5-stars', 'terror', 'read-in-2012', 'scary', 'contemporary']
Canonical:  ['Fiction', 'Mystery & Thriller', 'Contemporary', 'Horror', 'Fantasy', 'Young Adult', 'Classics']

Normalized: ['romance', 'kristen-ashley', 'erotica', 'contemporary romance', 'bdsm', 'contemporary', 'alpha-male', 'series', 'adult', 'erotic-romance', 'dnf', 'alpha-males', 'erotic', 'alpha', 'bad-boys', 'favourites', 'bad-boy', 're-read', 'steamy', 'ka', 'anti-hero', 'favorite', '5-stars', 'read-in-2012', 'audible', 'new-adult', 'chick-lit', 'fiction', 'ebooks', 'hot', 'dark', 'read-in-2013', '4-stars', 'adult-romance', 'm-f', 'romance-contemporary', 'alpha-hero', 'e-book', 'part-of-a-series', 'favorite-authors', 'dirty-talk', 'first-in-series', 'did-not-finish', 'books-i-own', 'read-in-2014', 'billionaire', 'faves', 'drama', 're-reads', 'all-time-favorites', 'mafia', '5-star', 'smut', 'reread', 'favorite-author', 'nook', 'read-2012', 'read-2013', 'favs', 'sexy', 'hot-hot-hot', 'audiobooks', 'kindle-books', 'author-kristen-ashley', 'read-in-2015', 'insta-love', 'hea', 'dirty-talker', 'book-boyfriends', 'lendable', 'favorite-series', 'maybe', 'ashley-kristen', '2013-reads', 'adult-fiction', 'alphas', '2012-reads', 'book-boyfriend', 'crime', 'read-2014', 'owned-books', 'guilty-pleasures', 'possessive', 'e-books', 'kristen-ashley-books', 'favorite-books', '3-stars', 'unfinished-hero', 'dark-romance', 'reviewed', 'read-in-2017', 'audio-book']
Canonical:  ['Fiction', 'Mystery & Thriller', 'Erotica', 'Contemporary', 'Romance']

In [63]:
from itertools import chain
from collections import defaultdict

# Recalculate and display the top 20 most frequent canonical genre tags
all_canonical_tags = defaultdict(int)
for tag in chain.from_iterable(df['canonical_genres']):
    all_canonical_tags[tag] += 1

print(f"Total unique canonical genre tags found: {len(all_canonical_tags)}")
print("Top 20 most frequent canonical genre tags:")
for tag, count in sorted(all_canonical_tags.items(), key=lambda item: item[1], reverse=True)[:20]:
    print(f"- {tag}: {count}")

Total unique canonical genre tags found: 28
Top 20 most frequent canonical genre tags:
- Fiction: 61013
- Romance: 43669
- Contemporary: 39244
- Fantasy: 31353
- Young Adult: 29238
- Mystery & Thriller: 28209
- Adventure: 19287
- Paranormal: 19199
- Science Fiction: 16948
- Historical Fiction: 15275
- Urban Fantasy: 12324
- Action: 11850
- Paranormal Romance: 10222
- Erotica: 9241
- Horror: 9051
- Non-Fiction: 8848
- Classics: 8017
- Dystopia: 7237
- Biography & Memoir: 5965
- LGBTQ+: 4352

## Final Quality Checks

In [65]:
print(f"Total number of rows in DataFrame: {len(df)}")

books_no_canonical_genre = df[df['canonical_genres'].apply(len) == 0]
print(f"Number of books with no canonical genre: {len(books_no_canonical_genre)}")

books_with_canonical_genre = df[df['canonical_genres'].apply(len) > 0]
print(f"Number of books with at least one canonical genre: {len(books_with_canonical_genre)}")

print("\nDistribution of the number of canonical genres per book:")
display(df['canonical_genres'].apply(len).value_counts().sort_index())

Total number of rows in DataFrame: 82855
Number of books with no canonical genre: 5204
Number of books with at least one canonical genre: 77651

Distribution of the number of canonical genres per book:

canonical_genres
0      5204
1      6293
2      7761
3     11211
4     13340
5      9320
6      6078
7      4867
8      4551
9      4574
10     4091
11     2710
12     1580
13      935
14      245
15       73
16       21
17        1
Name: count, dtype: int64

In [ ]:
# Cell removed for refactoring purposes as its content was superseded by cell 2bdda9a3

In [67]:
from itertools import chain
from collections import defaultdict

# Recalculate and display the top 20 most frequent canonical genre tags
all_canonical_tags = defaultdict(int)
for tag in chain.from_iterable(df['canonical_genres']):
    all_canonical_tags[tag] += 1

print(f"Total unique canonical genre tags found: {len(all_canonical_tags)}")
print("Top 20 most frequent canonical genre tags:")
for tag, count in sorted(all_canonical_tags.items(), key=lambda item: item[1], reverse=True)[:20]:
    print(f"- {tag}: {count}")

Total unique canonical genre tags found: 28
Top 20 most frequent canonical genre tags:
- Fiction: 61013
- Romance: 43669
- Contemporary: 39244
- Fantasy: 31353
- Young Adult: 29238
- Mystery & Thriller: 28209
- Adventure: 19287
- Paranormal: 19199
- Science Fiction: 16948
- Historical Fiction: 15275
- Urban Fantasy: 12324
- Action: 11850
- Paranormal Romance: 10222
- Erotica: 9241
- Horror: 9051
- Non-Fiction: 8848
- Classics: 8017
- Dystopia: 7237
- Biography & Memoir: 5965
- LGBTQ+: 4352

## Keep Multiple Genres Per Book

Unlike traditional single-genre classification, many books span multiple categories. This step acknowledges and preserves this multi-label nature by ensuring that all relevant canonical genres are kept for each book. The `canonical_genres` column already stores genres as lists, which inherently supports multiple genres per book.

In [69]:
# The 'canonical_genres' column, which we created in the previous step, naturally supports multiple genres per book as it stores a list of canonical genres.
# Therefore, this step primarily involves confirming that the data structure is suitable and optionally visualizing the distribution of books having multiple genres.

# Count how many genres each book has after canonical mapping
df['num_canonical_genres'] = df['canonical_genres'].apply(len)

print("Distribution of number of canonical genres per book:")
display(df['num_canonical_genres'].value_counts().sort_index())

print("\nSample of books with multiple canonical genres:")
display(df[df['num_canonical_genres'] > 1][['title', 'canonical_genres']].head(10))

print("\nBooks with no canonical genres (could be due to no matching tags in our map or all tags were non-genre):")
display(df[df['num_canonical_genres'] == 0][['title', 'normalized_genres']].head(10))

Distribution of number of canonical genres per book:

num_canonical_genres
0      5204
1      6293
2      7761
3     11211
4     13340
5      9320
6      6078
7      4867
8      4551
9      4574
10     4091
11     2710
12     1580
13      935
14      245
15       73
16       21
17        1
Name: count, dtype: int64

Sample of books with multiple canonical genres:

,title,canonical_genres
0,"Gathering Darkness (Falling Kingdoms, #3)","[Fiction, LGBTQ+, Romance, Fantasy, Young Adul..."
1,"Young Avengers, Volume 2: Alternative Culture","[Superhero, Science Fiction, Fiction, LGBTQ+, ..."
2,"Hail to the Chef (A White House Chef Mystery, #2)","[Contemporary, Romance, Fiction, Mystery & Thr..."
3,We Have Always Lived in the Castle,"[Fiction, Mystery & Thriller, Contemporary, Ho..."
4,"Knight (Unfinished Hero, #1)","[Fiction, Mystery & Thriller, Erotica, Contemp..."
5,"Hearts in Darkness (Hearts in Darkness, #1)","[Erotica, Contemporary, Romance, Fiction]"
6,The Honourable Schoolboy,"[Fiction, Mystery & Thriller, Action, Classics..."
7,"Pulse (Collide, #2)","[Fiction, Erotica, Contemporary, Romance, Youn..."
8,"Irresistible Desire (Savannah, #1)","[Erotica, Contemporary, Romance, Western]"
9,A Dog's Life: The Autobiography of a Stray,"[Middle Grade, Fiction, Contemporary, Biograph..."

Books with no canonical genres (could be due to no matching tags in our map or all tags were non-genre):

,title,normalized_genres
23,"His Dark Desires (Arrested by Passion, #1)",[series]
37,Bitter Melon,"[poetry, first-reads, giveaways]"
48,Legacy,"[new-adult-college, maybe]"
67,Crescent Vendetta (Vendetta Series Book 1),[shifters]
77,Torn: Part Nine,[]
98,The Gypsy Casts a Spell,[]
102,It's Hug Day!,[]
109,The Skeptical Feminist: Discovering the Virgin...,"[feminism, gender, non-fiction]"
120,Outlaw: The True Story of Claude Dallas,[idaho]
123,Accidentally Yours,[]

# Cell removed for refactoring purposes

In [ ]:
# Cell removed for refactoring purposes as its content was superseded by cell 5c5340d4

In [71]:
df.shape
df.head()

,user_id,book_id,is_read,rating,date_added,date_updated,read_at,started_at,reading_duration_days,title,...,genres,num_pages,original_title,original_publication_year,target,genres_list,cleaned_genres,normalized_genres,canonical_genres,num_canonical_genres
0,6ae8a47b5a7f8b0b145cf597a5d5c929,17342700,1,5,2016-12-21 11:23:08,2017-04-24 19:20:25,2017-04-24 00:00:00,2017-04-22,2.0,"Gathering Darkness (Falling Kingdoms, #3)",...,['to-read' 'young-adult' 'currently-reading' '...,416,Gathering Darkness,2014.0,0.0,"[to-read, young-adult, currently-reading, fant...","[young-adult, fantasy, books-i-own, ya, magic,...","[young adult, fantasy, books-i-own, young adul...","[Fiction, LGBTQ+, Romance, Fantasy, Young Adul...",8
1,0c7429f150417a1af3c7045fc89a3f4e,18513581,1,3,2016-07-23 07:06:57,2017-01-01 17:40:35,2016-12-10 00:00:00,2016-12-02,8.0,"Young Avengers, Volume 2: Alternative Culture",...,['to-read' 'comics' 'graphic-novels' 'marvel' ...,112,"Young Avengers, Volume 2: Alternative Culture",2014.0,0.0,"[to-read, comics, graphic-novels, marvel, grap...","[comics, graphic-novels, marvel, graphic-novel...","[graphic novel, graphic novel, marvel, graphic...","[Superhero, Science Fiction, Fiction, LGBTQ+, ...",11
2,cd75b15c85a3dd27fef5ec3403a5f873,3993755,1,0,2017-06-30 08:33:08,2017-06-30 08:33:26,2017-06-30 08:33:26,2017-06-29,1.0,"Hail to the Chef (A White House Chef Mystery, #2)",...,['to-read' 'mystery' 'cozy-mystery' 'cozy-myst...,328,"Hail to the Chef (White House Chef Mystery, Bo...",2008.0,NaN,"[to-read, mystery, cozy-mystery, cozy-mysterie...","[mystery, cozy-mystery, cozy-mysteries, myster...","[mystery, cozy-mystery, cozy-mysteries, myster...","[Contemporary, Romance, Fiction, Mystery & Thr...",4
3,86b931f21144e8d743b40dc26f82073c,89724,1,4,2011-10-07 13:43:08,2011-11-03 20:05:41,2011-10-13 00:00:00,2011-10-07,6.0,We Have Always Lived in the Castle,...,['to-read' 'horror' 'fiction' 'favorites' 'cur...,146,We Have Always Lived in the Castle,1962.0,1.0,"[to-read, horror, fiction, favorites, currentl...","[horror, fiction, classics, gothic, mystery, b...","[horror, fiction, classics, gothic, mystery, b...","[Fiction, Mystery & Thriller, Contemporary, Ho...",7
4,9adddbae754bf26fb04999a0f79f14c4,13565914,1,3,2013-01-03 18:42:59,2013-01-03 18:51:59,2013-01-04 18:51:59,2013-01-01,3.0,"Knight (Unfinished Hero, #1)",...,['to-read' 'favorites' 'romance' 'currently-re...,285,Knight,2012.0,1.0,"[to-read, favorites, romance, currently-readin...","[romance, kristen-ashley, erotica, contemporar...","[romance, kristen-ashley, erotica, contemporar...","[Fiction, Mystery & Thriller, Erotica, Contemp...",5

In [39]:
df.shape

(16000, 25)

In [72]:
df.shape

(82855, 25)

In [74]:
import pandas as pd
from google.colab import files

# Define the output filename for the final dataset including the target column
output_final_filename = 'final_cleaned_data_with_target.csv'

# Ensure df is available and contains the target column
if 'df' in locals() and not df.empty and 'target' in df.columns:
    print(f"Saving the final dataset to '{output_final_filename}'...")
    df.to_csv(output_final_filename, index=False)
    print(f"'{output_final_filename}' created successfully.")

#     # Download the file
#     print(f"Downloading '{output_final_filename}'...")
#     files.download(output_final_filename)
#     print(f"'{output_final_filename}' has been downloaded.")
# elif 'df' not in locals() or df.empty:
#     print("Error: The DataFrame 'df' was not found or is empty. Please ensure all previous steps were executed successfully.")
# else:
#     print("Error: The 'target' column was not found in 'df'. Please ensure the target column creation step was executed correctly.")

Saving the final dataset to 'final_cleaned_data_with_target.csv'...
'final_cleaned_data_with_target.csv' created successfully.
Downloading 'final_cleaned_data_with_target.csv'...

'final_cleaned_data_with_target.csv' has been downloaded.

In [75]:
import pandas as pd
df=pd.read_csv('final_cleaned_data_with_target.csv')
df.columns

/tmp/ipykernel_4144/1817052475.py:2: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('final_cleaned_data_with_target.csv')

Index(['user_id', 'book_id', 'is_read', 'rating', 'date_added', 'date_updated',
       'read_at', 'started_at', 'reading_duration_days', 'title', 'author_ids',
       'author_names', 'average_rating', 'publication_year', 'description',
       'genres', 'num_pages', 'original_title', 'original_publication_year',
       'target', 'genres_list', 'cleaned_genres', 'normalized_genres',
       'canonical_genres', 'num_canonical_genres'],
      dtype='object')

In [77]:
import re
import pandas as pd
df=pd.read_csv('final_cleaned_data_with_target.csv')
# 1. Parse IDs
# The 'author_ids' column appears to contain string representations of lists.
# We'll parse these into actual Python lists using regex, similar to genre parsing.

print(f"Original type of 'author_ids' column: {df['author_ids'].dtype}")
print(f"Sample of original 'author_ids' data:\n{df['author_ids'].head()}\n")

def parse_author_ids(ids_str):
    if pd.isna(ids_str) or not isinstance(ids_str, str):
        return []
    # Use regex to find all numbers (author IDs) within the string, treating them as strings initially
    # Example format: "['12345' '67890']" or similar, we want to extract '12345' and '67890'
    author_tags = re.findall(r"'([^']*)'", ids_str)
    # Ensure the extracted IDs are consistent, e.g., convert to int if they represent numerical IDs
    return [int(tag) if tag.isdigit() else tag for tag in author_tags]

df['author_id_list'] = df['author_ids'].apply(parse_author_ids)

print(f"New 'author_id_list' column created. Sample of parsed 'author_id_list' data:\n{df['author_id_list'].head()}\n")
print(f"Type of 'author_id_list' column: {df['author_id_list'].dtype}\n")

# 2. Handle multiple authors (already handled by creating 'author_id_list' as a list)

# 3. Select a consistent primary author representation
# For simplicity, we'll take the first author ID from the list as the primary author.
# If the list is empty, the primary_author_id will be NaN.
df['primary_author_id'] = df['author_id_list'].apply(lambda x: x[0] if x else None)

print(f"New 'primary_author_id' column created. Sample of data:\n{df['primary_author_id'].head()}\n")

# 4. Validate author IDs / missing values
# Check for books where no author IDs could be parsed or primary author is missing.

books_no_author_ids = df[df['author_id_list'].apply(len) == 0]
print(f"Number of books with no parsed author IDs: {len(books_no_author_ids)}")

books_missing_primary_author = df[df['primary_author_id'].isnull()]
print(f"Number of books with a missing primary author ID: {len(books_missing_primary_author)}")

print("\nValue counts for primary_author_id (top 10):")
display(df['primary_author_id'].value_counts().head(10))

/tmp/ipykernel_4144/1503876052.py:3: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('final_cleaned_data_with_target.csv')

Original type of 'author_ids' column: object
Sample of original 'author_ids' data:
0                     ['5295120' '38531']
1    ['439887' '221821' '504788' '93125']
2                             ['1020232']
3                        ['13388' '6404']
4                             ['2958084']
Name: author_ids, dtype: object

New 'author_id_list' column created. Sample of parsed 'author_id_list' data:
0                   [5295120, 38531]
1    [439887, 221821, 504788, 93125]
2                          [1020232]
3                      [13388, 6404]
4                          [2958084]
Name: author_id_list, dtype: object

Type of 'author_id_list' column: object

New 'primary_author_id' column created. Sample of data:
0    5295120.0
1     439887.0
2    1020232.0
3      13388.0
4    2958084.0
Name: primary_author_id, dtype: float64

Number of books with no parsed author IDs: 7
Number of books with a missing primary author ID: 7

Value counts for primary_author_id (top 10):

primary_author_id
3389.0       293
150038.0     235
1221698.0    209
3780.0       205
3433047.0    191
1077326.0    179
4684322.0    167
17061.0      163
137902.0     163
5430144.0    162
Name: count, dtype: int64

In [79]:
print("Author ID processing steps have already been performed.")
print("You can review the output from the previous cell (9N4jd0ca5u5j) for details.")
print("\nSummary of previous execution:")
print(f"Original type of 'author_ids' column: {df['author_ids'].dtype}")
print(f"Sample of original 'author_ids' data:\n{df['author_ids'].head()}\n")
print(f"New 'author_id_list' column created. Sample of parsed 'author_id_list' data:\n{df['author_id_list'].head()}\n")
print(f"Type of 'author_id_list' column: {df['author_id_list'].dtype}\n")
print(f"New 'primary_author_id' column created. Sample of data:\n{df['primary_author_id'].head()}\n")

books_no_author_ids = df[df['author_id_list'].apply(len) == 0]
print(f"Number of books with no parsed author IDs: {len(books_no_author_ids)}")

books_missing_primary_author = df[df['primary_author_id'].isnull()]
print(f"Number of books with a missing primary author ID: {len(books_missing_primary_author)}")

print("\nValue counts for primary_author_id (top 10):")
display(df['primary_author_id'].value_counts().head(10))

Author ID processing steps have already been performed.
You can review the output from the previous cell (9N4jd0ca5u5j) for details.

Summary of previous execution:
Original type of 'author_ids' column: object
Sample of original 'author_ids' data:
0                     ['5295120' '38531']
1    ['439887' '221821' '504788' '93125']
2                             ['1020232']
3                        ['13388' '6404']
4                             ['2958084']
Name: author_ids, dtype: object

New 'author_id_list' column created. Sample of parsed 'author_id_list' data:
0                   [5295120, 38531]
1    [439887, 221821, 504788, 93125]
2                          [1020232]
3                      [13388, 6404]
4                          [2958084]
Name: author_id_list, dtype: object

Type of 'author_id_list' column: object

New 'primary_author_id' column created. Sample of data:
0    5295120.0
1     439887.0
2    1020232.0
3      13388.0
4    2958084.0
Name: primary_author_id, dtype: float64

Number of books with no parsed author IDs: 7
Number of books with a missing primary author ID: 7

Value counts for primary_author_id (top 10):

primary_author_id
3389.0       293
150038.0     235
1221698.0    209
3780.0       205
3433047.0    191
1077326.0    179
4684322.0    167
17061.0      163
137902.0     163
5430144.0    162
Name: count, dtype: int64

In [36]:
df.shape

(16000, 27)

In [81]:
import pandas as pd
from google.colab import files

# Define the output filename for the final dataset including the target column
output_final_filename = 'final_cleaned_data.csv'

# Ensure df is available and contains the target column
if 'df' in locals() and not df.empty and 'target' in df.columns:
    print(f"Saving the final dataset to '{output_final_filename}'...")
    df.to_csv(output_final_filename, index=False)
    print(f"'{output_final_filename}' created successfully.")

    # Download the file
    print(f"Downloading '{output_final_filename}'...")
    files.download(output_final_filename)
    print(f"'{output_final_filename}' has been downloaded.")
elif 'df' not in locals() or df.empty:
    print("Error: The DataFrame 'df' was not found or is empty. Please ensure all previous steps were executed successfully.")
else:
    print("Error: The 'target' column was not found in 'df'. Please ensure the target column creation step was executed correctly.")

Saving the final dataset to 'final_cleaned_data.csv'...
'final_cleaned_data.csv' created successfully.
Downloading 'final_cleaned_data.csv'...

'final_cleaned_data.csv' has been downloaded.

In [82]:
df.shape

(82855, 27)